### ISSUE TITLE
Estilos del Header [3h]

### ISSUE THREAD

**Issue by LeonidasEsteban** [erickleaopm/narbel#1]
la parte superior del header tiene un pixel extra

![Captura de Pantalla 2020-03-30 a la(s) 6 29 26 p  m](https://user-images.githubusercontent.com/1150114/77974473-7fadd580-72b4-11ea-8c50-7d693820af1e.png)

**Comment by erickleaopm** [comment]
Se realizó la corrección sustituyendo la propiedad "border" por "box-shadow".
